# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner1_full_name', models.CharField(max_length=50)),
                ('partner2_full_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=20)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(max_length=80)),
                ('town_or_city', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('wedding_date', models.DateField()),
                ('ceremony_address', models.CharField(max_length=80)),
                ('reception_address', models.CharField(max_length=80)),
                ('rsvp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
